disable-update-checker: false

prefix: '&7[FlappyAC] '
violation-reset-delay: 300

messages:
  flag-to-console: false
  client-brand: "&2{player}'s &7client is &2{brand}"
  reload: "&7FlappyAC has been reloaded"
  violation-remove-invalid-player: "&7Invalid player name"
  alert-toggle:
    disable: "&7You will no longer receive alerts"
    enable: "&7You will receive alerts"
  violation-reset:
    all: '&7Violations reset'
    player: '&7Violations reset for &2{player}'
  failed-check: '&2{player} &7failed &2{check} &7VL: &2{vl}'
  punish:  |
    &7--------------------
    &2{player} &7has been caught cheating
    &7--------------------
  hover:  |
    &7TPS: &2{tps}
    &7Ping: &2{ping}

    &7Debug: &2{debug}

  commands:
    - 'tp {player}'
    - 'gamemode spectator'

checks:
  groundspoof:
    a:
      enabled: true
      min-tps: 17.0
      punishable: true
      broadcast-punishment: true
      punish-vl: 200
      punish-commands:
        - "kick {player} FlappyAC > Suspicious Activity"
      vl: 20
  badpackets:
    a:
      enabled: true
      min-tps: 17.0
      punishable: true
      broadcast-punishment: true
      punish-vl: 10
      punish-commands:
        - "kick {player} FlappyAC > Suspicious Activity"
      vl: 10
    b:
      enabled: true
      min-tps: 17.0
      punishable: true
      broadcast-punishment: true
      punish-vl: 200
      punish-commands:
        - "kick {player} FlappyAC > Suspicious Activity"
      vl: 10
  skinblinker:
    a:
      enabled: true
      min-tps: 17.0
      punishable: true
      broadcast-punishment: true
      punish-vl: 100
      punish-commands:
        - "kick {player} FlappyAC > Suspicious Activity"
      vl: 10
  blockplace:
    a:
      enabled: true
      min-tps: 17.0
      punishable: true
      broadcast-punishment: true
      punish-vl: 100
      punish-commands:
        - "kick {player} FlappyAC > Suspicious Activity"
      vl: 10
    b:
      enabled: true
      min-tps: 17.0
      punishable: true
      broadcast-punishment: true
      punish-vl: 100
      punish-commands:
        - "kick {player} FlappyAC > Suspicious Activity"
      vl: 10
  timer:
    a:
      enabled: true
      min-tps: 17.0
      punishable: true
      broadcast-punishment: true
      punish-vl: 200
      punish-commands:
        - "kick {player} FlappyAC > Suspicious Activity"
      vl: 10
  speed:
    a:
      enabled: true
      min-tps: 17.0
      punishable: true
      broadcast-punishment: true
      punish-vl: 200
      punish-commands:
        - "kick {player} FlappyAC > Suspicious Activity"
      vl: 10
  forcefield:
    a:
      enabled: true
      min-tps: 17.0
      punishable: true
      broadcast-punishment: true
      punish-vl: 200
      punish-commands:
        - "kick {player} FlappyAC > Suspicious Activity"
      vl: 10